name: learn-github-actions
run-name: ${{ github.actor }} merged some code
on: 
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
